<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userrpc.proto

namespace GPBMetadata;

class Userrpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a0d757365727270632e70726f746f120b4170702e5573657252706322300a094c6f67696e496e666f12110a096c6f67696e6e616d6518012001280912100a0870617373776f7264180220012809225a0a0855736572496e666f120c0a04636f6465180120012805120f0a076572725f6d7367180220012809120d0a05746f6b656e180320012809120e0a0675736572696418042001280512100a08757365726e616d6518052001280932440a0455736572123c0a09557365724c6f67696e12162e4170702e557365725270632e4c6f67696e496e666f1a152e4170702e557365725270632e55736572496e666f2200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

