<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userrpc.proto

namespace App\UserRpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.UserRpc.LoginInfo</code>
 */
class LoginInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string loginname = 1;</code>
     */
    protected $loginname = '';
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    protected $password = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $loginname
     *     @type string $password
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Userrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string loginname = 1;</code>
     * @return string
     */
    public function getLoginname()
    {
        return $this->loginname;
    }

    /**
     * Generated from protobuf field <code>string loginname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginname($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

}

